#!/usr/bin/env python3
"""Decode an animated GIF into a C++ header of palette-indexed frame data
for the party_parrot FTXUI app.

GIF transparency is a binary mask (no partial alpha blending), so each
composited pixel is treated as either fully opaque or fully transparent.
Requires Pillow: pip install pillow

Usage:
    python3 tools/gen_parrot_frames.py [gif_path] [header_out_path]

Defaults to Sun_Conure.gif -> src/party_parrot/parrot_frames.h.
"""

import sys
from pathlib import Path

from PIL import Image, ImageSequence

ALPHA_THRESHOLD = 128
VALUES_PER_LINE = 32


def load_frames(gif_path: Path):
    im = Image.open(gif_path)
    frames = []
    delay_ms = None
    for frame in ImageSequence.Iterator(im):
        if delay_ms is None:
            delay_ms = frame.info.get("duration", 40)
        frames.append(frame.convert("RGBA"))
    return frames, delay_ms


def build_palette_and_indices(frames):
    width, height = frames[0].size
    palette: list[tuple[int, int, int]] = []
    color_to_index: dict[tuple[int, int, int], int] = {}
    frame_indices: list[list[int]] = []

    for frame in frames:
        if frame.size != (width, height):
            raise SystemExit(f"frame size {frame.size} != {(width, height)}")
        pixels = frame.load()
        indices = [0] * (width * height)
        for y in range(height):
            row_base = y * width
            for x in range(width):
                r, g, b, a = pixels[x, y]
                if a < ALPHA_THRESHOLD:
                    indices[row_base + x] = -1  # fixed up once sentinel is known
                    continue
                key = (r, g, b)
                idx = color_to_index.get(key)
                if idx is None:
                    idx = len(palette)
                    color_to_index[key] = idx
                    palette.append(key)
                indices[row_base + x] = idx
        frame_indices.append(indices)

    sentinel = len(palette)
    if sentinel > 65535:
        raise SystemExit(f"too many distinct opaque colors: {sentinel}")

    for indices in frame_indices:
        for i, v in enumerate(indices):
            if v < 0:
                indices[i] = sentinel

    return width, height, palette, sentinel, frame_indices


def format_array(values, indent="    "):
    lines = []
    for i in range(0, len(values), VALUES_PER_LINE):
        chunk = values[i:i + VALUES_PER_LINE]
        lines.append(indent + ", ".join(str(v) for v in chunk) + ",")
    return "\n".join(lines)


def write_header(out_path: Path, width, height, delay_ms, palette, sentinel, frame_indices):
    idx_type = "uint8_t" if sentinel <= 255 else "uint16_t"
    frame_count = len(frame_indices)

    parts = []
    parts.append("// Generated by tools/gen_parrot_frames.py from Sun_Conure.gif.")
    parts.append("// Do not edit by hand -- regenerate instead.")
    parts.append("#pragma once")
    parts.append("")
    parts.append("#include <cstdint>")
    parts.append("")
    parts.append(f"constexpr int kFrameWidth = {width};")
    parts.append(f"constexpr int kFrameHeight = {height};")
    parts.append(f"constexpr int kFrameCount = {frame_count};")
    parts.append(f"constexpr int kFrameDelayMs = {delay_ms};")
    parts.append(f"constexpr int kTransparentIndex = {sentinel};")
    parts.append("")
    parts.append(f"constexpr uint8_t kPalette[{len(palette)}][3] = {{")
    palette_values = [f"{{{r}, {g}, {b}}}" for r, g, b in palette]
    for i in range(0, len(palette_values), 8):
        parts.append("    " + ", ".join(palette_values[i:i + 8]) + ",")
    parts.append("};")
    parts.append("")
    parts.append(f"constexpr {idx_type} kFrameIndices[{frame_count}][{width * height}] = {{")
    for indices in frame_indices:
        parts.append("  {")
        parts.append(format_array(indices, indent="    "))
        parts.append("  },")
    parts.append("};")
    parts.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(parts))


def main():
    gif_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("Sun_Conure.gif")
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("src/party_parrot/parrot_frames.h")

    frames, delay_ms = load_frames(gif_path)
    width, height, palette, sentinel, frame_indices = build_palette_and_indices(frames)

    print(f"frames={len(frames)} size={width}x{height} delay_ms={delay_ms} "
          f"distinct_colors={len(palette)} sentinel={sentinel}")

    write_header(out_path, width, height, delay_ms, palette, sentinel, frame_indices)
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
